/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import ejercicioconexion.EjercicioConexion;

/**
 *
 * @author a.regueira.fernandez
 */
public class Vista extends javax.swing.JFrame {

    EjercicioConexion controlador = new EjercicioConexion();
    /** Creates new form Vista */
    public Vista() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        nPedidoC = new javax.swing.JTextField();
        Consultar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nPedidoRes = new javax.swing.JLabel();
        fechaRes = new javax.swing.JLabel();
        nombreRes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Not1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NPedidoCP = new javax.swing.JTextField();
        fechaCP = new javax.swing.JTextField();
        nombreCP = new javax.swing.JTextField();
        CrearPedido = new javax.swing.JButton();
        NPedidoLP = new javax.swing.JTextField();
        descripcionLP = new javax.swing.JTextField();
        precioLP = new javax.swing.JTextField();
        cantidadLP = new javax.swing.JTextField();
        CrearLineaPedido = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        notificacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(35, 61, 77));

        jPanel1.setBackground(new java.awt.Color(161, 193, 129));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 225));

        label1.setText("label1");

        jLabel2.setText("jLabel2");

        nPedidoC.setBackground(new java.awt.Color(35, 61, 77));
        nPedidoC.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        nPedidoC.setForeground(new java.awt.Color(252, 202, 70));
        nPedidoC.setText("Nº Pedido");

        Consultar.setBackground(new java.awt.Color(252, 202, 70));
        Consultar.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        Consultar.setForeground(new java.awt.Color(35, 61, 77));
        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(35, 61, 77));
        jLabel4.setText("Numero de pedido:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(35, 61, 77));
        jLabel5.setText("Fecha de pedido:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(35, 61, 77));
        jLabel6.setText("Nombre de cliente:");

        nPedidoRes.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        nPedidoRes.setForeground(new java.awt.Color(35, 61, 77));
        nPedidoRes.setText("-");
        nPedidoRes.setName("nPedidoRes"); // NOI18N

        fechaRes.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        fechaRes.setForeground(new java.awt.Color(35, 61, 77));
        fechaRes.setText("-");
        fechaRes.setName("fechaRes"); // NOI18N

        nombreRes.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        nombreRes.setForeground(new java.awt.Color(35, 61, 77));
        nombreRes.setText("-");
        nombreRes.setName("NombreRes"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(35, 61, 77));
        jLabel3.setText("Consulta pedidos");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(35, 61, 77));
        jLabel7.setText("-");

        Not1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Not1.setForeground(new java.awt.Color(35, 61, 77));
        Not1.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(nPedidoC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Consultar)
                                .addGap(77, 77, 77)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nPedidoRes)
                            .addComponent(nombreRes)
                            .addComponent(fechaRes)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Not1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nPedidoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(nPedidoRes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fechaRes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(nombreRes))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(Consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(Not1)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(120, 120, 120))
        );

        jPanel2.setBackground(new java.awt.Color(97, 155, 138));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 225));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 61, 77));
        jLabel1.setText("Crear pedidos");

        NPedidoCP.setBackground(new java.awt.Color(35, 61, 77));
        NPedidoCP.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        NPedidoCP.setForeground(new java.awt.Color(252, 202, 70));
        NPedidoCP.setText("Nº de Pedido");
        NPedidoCP.setName("lbNPedido"); // NOI18N
        NPedidoCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NPedidoCPActionPerformed(evt);
            }
        });

        fechaCP.setBackground(new java.awt.Color(35, 61, 77));
        fechaCP.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        fechaCP.setForeground(new java.awt.Color(252, 202, 70));
        fechaCP.setText("dd/mm/aaaa");
        fechaCP.setName("lbFecha"); // NOI18N
        fechaCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaCPActionPerformed(evt);
            }
        });

        nombreCP.setBackground(new java.awt.Color(35, 61, 77));
        nombreCP.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        nombreCP.setForeground(new java.awt.Color(252, 202, 70));
        nombreCP.setText("Nombre Cliente");
        nombreCP.setName("lbNombreCliente"); // NOI18N

        CrearPedido.setBackground(new java.awt.Color(252, 202, 70));
        CrearPedido.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        CrearPedido.setForeground(new java.awt.Color(35, 61, 77));
        CrearPedido.setText("Crear pedido");
        CrearPedido.setName("btCrearPedido"); // NOI18N
        CrearPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPedidoActionPerformed(evt);
            }
        });

        NPedidoLP.setBackground(new java.awt.Color(35, 61, 77));
        NPedidoLP.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        NPedidoLP.setForeground(new java.awt.Color(252, 202, 70));
        NPedidoLP.setText("Nº de Pedido");

        descripcionLP.setBackground(new java.awt.Color(35, 61, 77));
        descripcionLP.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        descripcionLP.setForeground(new java.awt.Color(252, 202, 70));
        descripcionLP.setText("Descripción");

        precioLP.setBackground(new java.awt.Color(35, 61, 77));
        precioLP.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        precioLP.setForeground(new java.awt.Color(252, 202, 70));
        precioLP.setText("Precio");

        cantidadLP.setBackground(new java.awt.Color(35, 61, 77));
        cantidadLP.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        cantidadLP.setForeground(new java.awt.Color(252, 202, 70));
        cantidadLP.setText("Cantidad");

        CrearLineaPedido.setBackground(new java.awt.Color(252, 202, 70));
        CrearLineaPedido.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        CrearLineaPedido.setForeground(new java.awt.Color(35, 61, 77));
        CrearLineaPedido.setText("Crear linea pedido");
        CrearLineaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearLineaPedidoActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(35, 61, 77));
        jSeparator1.setForeground(new java.awt.Color(35, 61, 77));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        notificacion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        notificacion.setForeground(new java.awt.Color(35, 61, 77));
        notificacion.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(NPedidoCP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaCP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreCP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CrearPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(descripcionLP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(NPedidoLP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadLP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precioLP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CrearLineaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(notificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NPedidoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CrearPedido))
                        .addGap(49, 49, 49)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantidadLP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NPedidoLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(precioLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descripcionLP))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CrearLineaPedido)
                        .addGap(34, 34, 34)))
                .addGap(29, 29, 29)
                .addComponent(notificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPedidoActionPerformed
        String txt = controlador.crearPedido(Integer.parseInt(NPedidoCP.getText()), fechaCP.getText(), nombreCP.getText());
        notificacion.setText(txt);
    }//GEN-LAST:event_CrearPedidoActionPerformed

    private void fechaCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaCPActionPerformed

    }//GEN-LAST:event_fechaCPActionPerformed

    private void NPedidoCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NPedidoCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NPedidoCPActionPerformed

    private void CrearLineaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearLineaPedidoActionPerformed
        String txt = controlador.crearLineaPedido(Integer.parseInt(NPedidoLP.getText()), descripcionLP.getText(), Double.parseDouble(cantidadLP.getText()), Double.parseDouble(precioLP.getText()));
        notificacion.setText(txt);
    }//GEN-LAST:event_CrearLineaPedidoActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        String[] txt = controlador.get(Integer.parseInt(nPedidoC.getText()));
        javax.swing.JLabel[] labels = {Not1, fechaRes, nombreRes};
        nPedidoRes.setText(nPedidoC.getText());
        if(txt != null){
            for(int i= 0; i < txt.length; i++ ){
                labels[i].setText(txt[i]);
            }
        }else{
            fechaRes.setText("No encontrado");
            nombreRes.setText("No encontrado");
        }
    }//GEN-LAST:event_ConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar;
    private javax.swing.JButton CrearLineaPedido;
    private javax.swing.JButton CrearPedido;
    private javax.swing.JTextField NPedidoCP;
    private javax.swing.JTextField NPedidoLP;
    private javax.swing.JLabel Not1;
    private javax.swing.JTextField cantidadLP;
    private javax.swing.JTextField descripcionLP;
    private javax.swing.JTextField fechaCP;
    private javax.swing.JLabel fechaRes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label1;
    private javax.swing.JTextField nPedidoC;
    private javax.swing.JLabel nPedidoRes;
    private javax.swing.JTextField nombreCP;
    private javax.swing.JLabel nombreRes;
    private javax.swing.JLabel notificacion;
    private javax.swing.JTextField precioLP;
    // End of variables declaration//GEN-END:variables

   

    
    
}
